# Generated by Django 4.1 on 2024-12-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lossreport',
            name='报损类型',
            field=models.CharField(choices=[('地内报损', '地内报损'), ('销售报损', '销售报损'), ('打包报损', '打包报损')], max_length=50, verbose_name='报损类型'),
        ),
    ]
