# Generated by Django 4.1 on 2024-12-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculture_cost',
            name='单价',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agriculture_cost',
            name='金额',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='baseinfoworkhour',
            name='单价',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costagriculture',
            name='单价',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costagriculture',
            name='单位',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costagriculture',
            name='单据编号',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costagriculture',
            name='商品全名',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costagriculture',
            name='地块',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costagriculture',
            name='数量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costagriculture',
            name='规格',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costagriculture',
            name='金额',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='其他资产',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='农家肥',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='出勤奖',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='地租',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='基地经理',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='大棚喷灌',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='大棚棚膜',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='大棚管架',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='散装工时',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='有机肥',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='服务费',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='材料',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='水电费',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='生活费',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='管理费',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costlandpreparation',
            name='单价',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costlandpreparation',
            name='单位',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costlandpreparation',
            name='实际打药面积',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costlandpreparation',
            name='数量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costlandpreparation',
            name='金额',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costlandpreparation',
            name='面积',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costpesticide',
            name='单价',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costpesticide',
            name='单位',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costpesticide',
            name='地块',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costpesticide',
            name='实际打药面积',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costpesticide',
            name='数量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costpesticide',
            name='金额',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costpesticide',
            name='面积',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costtotal',
            name='人工费用',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costtotal',
            name='农资费用',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costtotal',
            name='出库',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costtotal',
            name='打地费用',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costtotal',
            name='打药费用',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costtotal',
            name='折旧费用',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costtotal',
            name='销售',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='面积',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='dailypricereport',
            name='价格',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='dailypricereport',
            name='价格上限',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='价格上限'),
        ),
        migrations.AlterField(
            model_name='depreciationallocation',
            name='其他资产',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='其他资产'),
        ),
        migrations.AlterField(
            model_name='depreciationallocation',
            name='地租',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='地租'),
        ),
        migrations.AlterField(
            model_name='depreciationallocation',
            name='大棚喷灌',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='大棚喷灌'),
        ),
        migrations.AlterField(
            model_name='depreciationallocation',
            name='大棚棚膜',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='大棚棚膜'),
        ),
        migrations.AlterField(
            model_name='depreciationallocation',
            name='大棚管架',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='大棚管架'),
        ),
        migrations.AlterField(
            model_name='depreciationallocation',
            name='材料',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='材料'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='其他费用',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='其他费用'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='其他资产',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='其他资产'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='农家肥',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='农家肥'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='出勤奖',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='出勤奖'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='地租',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='地租'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='地租大棚摊销',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='地租大棚摊销'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='报销费用',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='报销费用'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='散工工时',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='散工工时'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='有机肥',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='有机肥'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='服务费',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='服务费'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='材料费',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='材料费'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='水电费',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='水电费'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='浇水打杂费用',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='浇水打杂费用'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='燃油费',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='燃油费'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='生活费',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='生活费'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='管理费1',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='管理费1'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='维修费',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='维修费'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='草莓土',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='草莓土'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='销售费',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='销售费'),
        ),
        migrations.AlterField(
            model_name='lossreport',
            name='报损数量',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='报损数量'),
        ),
        migrations.AlterField(
            model_name='lossreport',
            name='报损面积',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='五天种植单位亩',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='每天产量单位吨',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='每天种植单位亩',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='面积',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outboundrecord',
            name='数量_筐',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='数量/筐'),
        ),
        migrations.AlterField(
            model_name='outboundrecord',
            name='重量_kg',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='重量/kg'),
        ),
        migrations.AlterField(
            model_name='plandaily',
            name='面积',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='总产量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='总亩产',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='总周期天数',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='正常产量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='正常亩产',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='点子数量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='生长周期',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='移栽数量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='移栽板量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='销毁备注',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='销毁面积',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='面积',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plansummary',
            name='实际种植',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plansummary',
            name='实际采收',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plansummary',
            name='实际销售',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plansummary',
            name='损耗',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plansummary',
            name='生长周期',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plansummary',
            name='计划实际采收率',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plansummary',
            name='计划种植',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plansummary',
            name='计划达成率',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plansummary',
            name='计划销售率',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plansummary',
            name='预估客销售',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='吹生菜周期',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='总产量',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='总亩产',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='总周期天数',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='打地周期',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='施肥周期',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='正常产量',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='正常亩产',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='清棚周期',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='点籽周期',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='生长周期',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='移栽周期',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='采收周期',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='销毁面积',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='间菜周期',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='除草周期',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='面积',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='实际总产量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='总亩产量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='总周期',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='正常亩产量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='正常总产量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='生长周期',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='销毁面积',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='面积',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionwage',
            name='合计工资',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionwage',
            name='工价',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionwage',
            name='工时',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionwage',
            name='数量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionwage',
            name='累计工时',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='单价',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='重量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='销售额',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesoutbound',
            name='单位',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesoutbound',
            name='数量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesoutbound',
            name='重量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='单价',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='实收金额',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='实收金额'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='实销筐数',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='实销筐数'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='应收金额',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='应收金额'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='数量',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='金额',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='上车拨入框数',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='单价',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='单位',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='合计框数',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='实收金额',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='实收金额合计',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='差额',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='应收金额',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='应收金额合计',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='数量',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='本车拨入框数',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='规格',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='工资'),
        ),
    ]
