# Generated by Django 4.1 on 2025-03-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_agriculture_cost_单价_alter_agriculture_cost_金额_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciationallocation',
            name='月份',
            field=models.DateField(default='2025-03-01', verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='移栽日期',
            field=models.DateField(blank=True, null=True),
        ),
    ]
