# Generated by Django 4.1 on 2024-12-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_lossreport_报损类型'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[], default=1, verbose_name='二级分类'),
        ),
    ]
