# Generated by Django 4.1 on 2025-03-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_depreciationallocation_月份_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_batch',
            name='移栽日期',
            field=models.DateField(blank=True, null=True),
        ),
    ]
