# Generated by Django 4.1 on 2024-12-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default='', max_length=64, verbose_name='二级分类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=64, verbose_name='二级工种'),
        ),
    ]
