# Generated by Django 4.1 on 2024-12-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_order_title_order_category_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_batch',
            name='收苗单位',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='收苗数量',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='收苗时间',
            field=models.DateField(blank=True, null=True),
        ),
    ]
