# Generated by Django 4.1 on 2025-03-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_plant_batch_移栽日期'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plant_batch',
            unique_together={('批次ID', '地块')},
        ),
    ]
