# Generated by Django 4.1 on 2024-12-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_plant_batch_收苗单位_plant_batch_收苗数量_plant_batch_收苗时间'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_batch',
            name='收苗单位',
            field=models.CharField(blank=True, default='板', max_length=50, null=True),
        ),
    ]
