# Generated by Django 4.1 on 2025-03-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_plant_batch_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_batch',
            name='批次ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
