# Generated by Django 4.1 on 2024-12-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_plant_batch_收苗单位'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant_batch',
            old_name='收苗时间',
            new_name='收苗开始时间',
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='收苗结束开始',
            field=models.DateField(blank=True, null=True),
        ),
    ]
