# Generated by Django 4.1 on 2024-12-12 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_rename_收苗时间_plant_batch_收苗开始时间_plant_batch_收苗结束开始'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant_batch',
            old_name='收苗结束开始',
            new_name='收苗结束时间',
        ),
    ]
