# Generated by Django 4.1 on 2024-12-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_rename_收苗结束开始_plant_batch_收苗结束时间'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundrecord',
            name='挑菜',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='挑菜'),
        ),
    ]
