# Generated by Django 4.1 on 2024-05-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_baseinfobase_baseinfoproduct_baseinfoworkhour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfoworktype',
            name='工种级别',
            field=models.CharField(default='', max_length=2),
        ),
    ]
