# Generated by Django 4.1 on 2024-05-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_baseinfoworktype_工种级别'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfoworktype',
            name='父工种',
            field=models.CharField(default='', max_length=2),
        ),
    ]
