# Generated by Django 4.1 on 2024-05-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_baseinfoworktype_父工种'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planplantbatch',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
