# Generated by Django 4.1 on 2024-05-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_planplantbatch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfoworktype',
            name='父工种',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='feather', to='app01.baseinfoworktype'),
        ),
    ]
