# Generated by Django 4.1 on 2024-05-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_baseinfoworktype_父工种'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfoworktype',
            name='工种级别',
            field=models.IntegerField(choices=[(1, '1级分类'), (2, '2级分类')], default=1),
        ),
    ]
