# Generated by Django 4.1 on 2024-05-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_baseinfoworktype_工种级别'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfoworktype',
            name='父工种',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feather', to='app01.baseinfoworktype'),
        ),
    ]
