# Generated by Django 4.1 on 2024-05-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_baseinfoworktype_父工种'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfoworktype',
            name='父工种',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
