# Generated by Django 4.1 on 2024-05-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_alter_baseinfoworktype_父工种'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseinfoworkhour',
            old_name='分类',
            new_name='一级分类',
        ),
        migrations.AddField(
            model_name='baseinfoworkhour',
            name='二级分类',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
