# Generated by Django 4.1 on 2024-05-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_rename_分类_baseinfoworkhour_一级分类_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfoworkhour',
            name='二级分类',
            field=models.CharField(choices=[], max_length=255, null=True),
        ),
    ]
