# Generated by Django 4.1 on 2024-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_alter_baseinfoworkhour_二级分类'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='count',
        ),
        migrations.RemoveField(
            model_name='city',
            name='img',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='excel_file',
            field=models.FileField(default='', max_length=128, upload_to='city/', verbose_name='excel_file'),
        ),
        migrations.AddField(
            model_name='city',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='上传时间'),
        ),
        migrations.AddField(
            model_name='city',
            name='update_user',
            field=models.CharField(default='admin', max_length=100, verbose_name='人口'),
        ),
    ]
