# Generated by Django 4.2.13 on 2024-05-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_remove_city_count_remove_city_img_remove_city_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionwage',
            old_name='二级工种',
            new_name='一级分类',
        ),
        migrations.RenameField(
            model_name='productionwage',
            old_name='单位',
            new_name='二级分类',
        ),
        migrations.RenameField(
            model_name='productionwage',
            old_name='加班工时',
            new_name='累计工时',
        ),
        migrations.RemoveField(
            model_name='productionwage',
            name='单价',
        ),
        migrations.RemoveField(
            model_name='productionwage',
            name='数量',
        ),
        migrations.AddField(
            model_name='productionwage',
            name='工种',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='update_user',
            field=models.CharField(default='admin', max_length=100, verbose_name='上传人'),
        ),
    ]
