# Generated by Django 4.2.13 on 2024-05-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_rename_二级工种_productionwage_一级分类_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionwage',
            name='工人',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
