# Generated by Django 4.1 on 2024-05-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_productionwage_工价'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='uploader',
        ),
        migrations.AddField(
            model_name='productionwage',
            name='基地',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productionwage',
            name='数量',
            field=models.FloatField(null=True),
        ),
    ]
