# Generated by Django 4.1 on 2024-05-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_rename_city_uploader_productionwage_基地_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='agriculture_cost',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('日期', models.DateField(null=True)),
                ('工种', models.CharField(max_length=255, null=True)),
                ('数量', models.FloatField(null=True)),
                ('农资种类', models.CharField(max_length=255, null=True)),
                ('名称', models.CharField(max_length=255, null=True)),
                ('单价', models.FloatField(null=True)),
                ('金额', models.FloatField(null=True)),
                ('批次', models.CharField(max_length=255, null=True)),
                ('地块', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
