# Generated by Django 4.1 on 2024-05-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_agriculture_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculture_cost',
            name='日期',
            field=models.DateField(blank=True, null=True),
        ),
    ]
