# Generated by Django 4.1 on 2024-05-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_alter_agriculture_cost_日期'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculture_cost',
            name='数量',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
