# Generated by Django 4.1 on 2024-05-30 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_alter_agriculture_cost_数量'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_batch',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('批次ID', models.CharField(max_length=10, null=True)),
                ('品种', models.CharField(max_length=255, null=True)),
                ('品类', models.CharField(max_length=255, null=True)),
                ('地块', models.CharField(max_length=255, null=True)),
                ('面积', models.FloatField(null=True)),
                ('基地经理', models.CharField(blank=True, max_length=255, null=True)),
                ('移栽日期', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('移栽板量', models.FloatField(blank=True, null=True)),
                ('移栽数量', models.FloatField(blank=True, null=True)),
                ('点籽日期', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('用籽量', models.FloatField(blank=True, null=True)),
                ('备注', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
