# Generated by Django 4.1 on 2024-05-31 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_plant_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionwage',
            name='日期',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
