# Generated by Django 4.1 on 2024-05-31 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_alter_productionwage_日期'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionwage',
            name='日期',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
