# Generated by Django 4.1 on 2024-06-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_baseinfobase_面积'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfobase',
            name='基地位置',
            field=models.CharField(max_length=255),
        ),
    ]
