# Generated by Django 4.1 on 2024-06-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0033_alter_baseinfobase_基地位置'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseinfobase',
            old_name='基地位置',
            new_name='代号',
        ),
        migrations.RenameField(
            model_name='baseinfobase',
            old_name='基地名称',
            new_name='基地',
        ),
    ]
