# Generated by Django 4.1 on 2024-06-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0034_rename_基地位置_baseinfobase_代号_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionwage',
            name='负责人',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
