# Generated by Django 4.1 on 2024-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0035_productionwage_负责人'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionwage',
            name='合计工资',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
