# Generated by Django 4.1 on 2024-06-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0037_alter_agriculture_cost_单价_alter_agriculture_cost_金额_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionwage',
            name='备注',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
