# Generated by Django 4.1 on 2024-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0039_alter_productionwage_备注'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_by_plople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('公司', models.CharField(max_length=100)),
                ('归属业主', models.CharField(max_length=100)),
                ('姓名', models.CharField(max_length=100)),
                ('清棚', models.DecimalField(decimal_places=2, max_digits=10)),
                ('点籽', models.DecimalField(decimal_places=2, max_digits=10)),
                ('移栽', models.DecimalField(decimal_places=2, max_digits=10)),
                ('锄草', models.DecimalField(decimal_places=2, max_digits=10)),
                ('间菜', models.DecimalField(decimal_places=2, max_digits=10)),
                ('拔草', models.DecimalField(decimal_places=2, max_digits=10)),
                ('打药', models.DecimalField(decimal_places=2, max_digits=10)),
                ('施肥', models.DecimalField(decimal_places=2, max_digits=10)),
                ('吹生菜', models.DecimalField(decimal_places=2, max_digits=10)),
                ('插竹竿绑线', models.DecimalField(decimal_places=2, max_digits=10)),
                ('收菜', models.DecimalField(decimal_places=2, max_digits=10)),
                ('清废菜', models.DecimalField(decimal_places=2, max_digits=10)),
                ('绑线', models.DecimalField(decimal_places=2, max_digits=10)),
                ('散工', models.DecimalField(decimal_places=2, max_digits=10)),
                ('修枝', models.DecimalField(decimal_places=2, max_digits=10)),
                ('绑枝', models.DecimalField(decimal_places=2, max_digits=10)),
                ('插竹竿', models.DecimalField(decimal_places=2, max_digits=10)),
                ('其它', models.DecimalField(decimal_places=2, max_digits=10)),
                ('铲沟草', models.DecimalField(decimal_places=2, max_digits=10)),
                ('锄拔草', models.DecimalField(decimal_places=2, max_digits=10)),
                ('合计工时', models.DecimalField(decimal_places=2, max_digits=10)),
                ('合计工资', models.DecimalField(decimal_places=2, max_digits=10)),
                ('平均工资', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': '工资花名册',
                'verbose_name_plural': '工资花名册',
                'db_table': '工资花名册',
            },
        ),
    ]
