# Generated by Django 4.1 on 2024-06-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0041_alter_salary_by_plople_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary_by_plople',
        ),
    ]
