# Generated by Django 4.1 on 2024-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0048_alter_workhour_by_daily_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfoworkhour',
            name='默认计入成本',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='是', max_length=2),
        ),
    ]
