# Generated by Django 4.1 on 2024-06-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0049_alter_baseinfoworkhour_默认计入成本'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseinfoworktype',
            old_name='工种名称',
            new_name='分类名称',
        ),
        migrations.RenameField(
            model_name='baseinfoworktype',
            old_name='工种级别',
            new_name='分类级别',
        ),
        migrations.RenameField(
            model_name='baseinfoworktype',
            old_name='父工种',
            new_name='父分类',
        ),
    ]
