# Generated by Django 4.1 on 2024-07-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0050_rename_工种名称_baseinfoworktype_分类名称_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant_batch',
            old_name='品种',
            new_name='一级分类',
        ),
        migrations.RenameField(
            model_name='plant_batch',
            old_name='品类',
            new_name='二级分类',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '移栽'), (2, '采收')], default=1, verbose_name='二级分类'),
        ),
    ]
