# Generated by Django 4.1 on 2024-07-18 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0051_rename_品种_plant_batch_一级分类_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_batch',
            name='update_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='uploader',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
