# Generated by Django 4.1 on 2024-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0052_plant_batch_update_date_plant_batch_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='update_user',
            field=models.CharField(max_length=100, verbose_name='上传人'),
        ),
    ]
