# Generated by Django 4.1 on 2024-07-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0054_plant_batch_下批前一天_plant_batch_总产量_plant_batch_总亩产_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_batch',
            name='采收初期',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='采收末期',
            field=models.DateField(default=None),
        ),
    ]
