# Generated by Django 4.1 on 2024-07-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0057_alter_plant_batch_采收初期_alter_plant_batch_采收末期'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planplantbatch',
            name='下批前一天时间',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='采收初期',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='采收末期',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
