# Generated by Django 4.1 on 2024-07-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0059_remove_plant_batch_下批前一天_remove_plant_batch_总产量_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planplantbatch',
            name='下批前一天时间',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='采收初期',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='planplantbatch',
            name='采收末期',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='update_user',
            field=models.CharField(default='admin', max_length=100, verbose_name='上传人'),
        ),
    ]
