# Generated by Django 4.1 on 2024-07-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0062_alter_plant_batch_下批前一天时间_alter_plant_batch_周期_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_batch',
            name='一级分类',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='二级分类',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='周期批次',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='地块',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='批次ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='生长周期',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='采收期',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='面积',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
