# Generated by Django 4.1 on 2024-07-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0063_alter_plant_batch_一级分类_alter_plant_batch_二级分类_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('管理费', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='管理费')),
                ('生活费', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='生活费')),
                ('水电费', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='水电费')),
                ('服务费', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='服务费')),
                ('其他费用', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='其他费用')),
                ('燃油费', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='燃油费')),
                ('维修费', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='维修费')),
                ('出勤奖金', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出勤奖金')),
                ('销售费', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售费')),
            ],
            options={
                'verbose_name': '费用摊销',
                'verbose_name_plural': '费用摊销',
            },
        ),
        migrations.AlterField(
            model_name='uploader',
            name='update_user',
            field=models.CharField(default='', max_length=100, verbose_name='上传人'),
        ),
    ]
