# Generated by Django 4.1 on 2024-07-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0064_expenseallocation_alter_uploader_update_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseallocation',
            name='基地经理',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app01.baseinfobase', verbose_name='基地经理'),
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='月份',
            field=models.DateField(default='2024-07-01', verbose_name='月份'),
        ),
    ]
