# Generated by Django 4.1 on 2024-07-19 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0065_expenseallocation_基地经理_expenseallocation_月份'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseallocation',
            name='基地经理',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.baseinfobase', verbose_name='基地经理'),
        ),
    ]
