# Generated by Django 4.1 on 2024-07-19 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0067_alter_expenseallocation_基地经理'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('地租', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='地租')),
                ('大棚管架', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='大棚管架')),
                ('大棚棚膜', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='大棚棚膜')),
                ('大棚喷灌', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='大棚喷灌')),
                ('其他资产', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='其他资产')),
                ('材料', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='材料')),
                ('月份', models.DateField(default='2024-07-01', verbose_name='月份')),
                ('基地经理', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.baseinfobase', verbose_name='基地经理')),
            ],
            options={
                'verbose_name': '折旧摊销',
                'verbose_name_plural': '折旧摊销',
            },
        ),
    ]
