# Generated by Django 4.1 on 2024-07-19 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0068_depreciationallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('报损时间', models.DateTimeField(default=datetime.datetime.now, verbose_name='报损时间')),
                ('报损人', models.CharField(max_length=255, verbose_name='报损人')),
                ('批次', models.CharField(max_length=255, verbose_name='批次')),
                ('报损地块', models.CharField(max_length=255, verbose_name='报损地块')),
                ('报损类型', models.CharField(choices=[('地内报损', '地内报损'), ('销售报损', '销售报损')], max_length=50, verbose_name='报损类型')),
                ('报损数量', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='报损数量')),
                ('报损单位', models.CharField(max_length=50, verbose_name='报损单位')),
            ],
            options={
                'verbose_name': '报损',
                'verbose_name_plural': '报损',
            },
        ),
    ]
