# Generated by Django 4.1 on 2024-07-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0070_salesperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('车牌', models.CharField(max_length=50, unique=True, verbose_name='车牌')),
                ('司机', models.CharField(max_length=255, verbose_name='司机')),
                ('电话', models.CharField(max_length=20, verbose_name='电话')),
                ('型号', models.CharField(max_length=255, verbose_name='型号')),
                ('颜色', models.CharField(max_length=255, verbose_name='颜色')),
                ('类型', models.CharField(max_length=255, verbose_name='类型')),
                ('备注', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '车辆管理',
                'verbose_name_plural': '车辆管理',
            },
        ),
    ]
