# Generated by Django 4.1 on 2024-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0071_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('市场名称', models.CharField(max_length=255, unique=True, verbose_name='市场名称')),
                ('地区', models.CharField(max_length=255, verbose_name='地区')),
                ('地址', models.CharField(max_length=255, verbose_name='地址')),
                ('联系人', models.CharField(max_length=255, verbose_name='联系人')),
                ('插入时间', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
            ],
            options={
                'verbose_name': '市场信息',
            },
        ),
    ]
