# Generated by Django 4.1 on 2024-07-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0072_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('客户名称', models.CharField(max_length=255, verbose_name='客户名称')),
                ('联系人', models.CharField(max_length=255, verbose_name='联系人')),
                ('联系电话', models.CharField(max_length=20, verbose_name='联系电话')),
                ('邮箱', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('地址', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('销售地区', models.CharField(max_length=255, verbose_name='销售地区')),
                ('客户类型', models.CharField(choices=[('个人', '个人'), ('企业', '企业')], max_length=50, verbose_name='客户类型')),
                ('公司名称', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司名称')),
                ('公司网站', models.URLField(blank=True, null=True, verbose_name='公司网站')),
                ('公司地址', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司地址')),
                ('行业', models.CharField(blank=True, max_length=255, null=True, verbose_name='行业')),
                ('备注', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('创建时间', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('更新时间', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
    ]
