# Generated by Django 4.1 on 2024-07-22 08:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0073_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('日期', models.DateField(default=django.utils.timezone.now, null=True)),
                ('公司', models.CharField(max_length=255, verbose_name='公司')),
                ('规格', models.CharField(max_length=255, verbose_name='规格')),
                ('单位', models.CharField(max_length=255, verbose_name='单位')),
                ('数量', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量')),
                ('重量', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='重量')),
                ('批次', models.CharField(max_length=255, verbose_name='批次')),
                ('地块', models.CharField(max_length=255, verbose_name='地块')),
                ('备注', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('一级分类', models.ForeignKey(limit_choices_to={'分类级别': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='一级分类', to='app01.baseinfoworktype', verbose_name='一级分类')),
                ('二级分类', models.ForeignKey(limit_choices_to={'分类级别': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='二级分类', to='app01.baseinfoworktype', verbose_name='二级分类')),
                ('市场', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.market', verbose_name='市场')),
                ('车牌', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.vehicle', verbose_name='车牌')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录',
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('客户', models.CharField(max_length=255, verbose_name='客户')),
                ('数量', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量')),
                ('单价', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('金额', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='金额')),
                ('应收金额', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收金额')),
                ('实收金额', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实收金额')),
                ('备注', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('出库记录', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='app01.outboundrecord')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录',
            },
        ),
    ]
