# Generated by Django 4.1 on 2024-07-20 07:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0073_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('日期', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('公司', models.CharField(max_length=255, verbose_name='公司')),
                ('一级分类', models.CharField(max_length=255, verbose_name='一级分类')),
                ('二级分类', models.CharField(max_length=255, verbose_name='二级分类')),
                ('规格', models.CharField(max_length=255, verbose_name='规格')),
                ('单位', models.CharField(max_length=50, verbose_name='单位')),
                ('数量', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('重量', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='重量')),
                ('批次', models.CharField(max_length=255, verbose_name='批次')),
                ('地块', models.CharField(max_length=255, verbose_name='地块')),
                ('备注', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('市场', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.market', verbose_name='市场')),
                ('车牌', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.vehicle', verbose_name='车牌')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录',
            },
        ),
    ]
