# Generated by Django 4.1 on 2024-07-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0074_outboundrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundrecord',
            name='一级分类',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='一级分类', to='app01.baseinfoworktype', verbose_name='一级分类'),
        ),
        migrations.AlterField(
            model_name='outboundrecord',
            name='二级分类',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='二级分类', to='app01.baseinfoworktype', verbose_name='二级分类'),
        ),
    ]
