# Generated by Django 4.1 on 2024-07-25 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0074_outboundrecord_salesrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='批次',
            field=models.CharField(default=None, max_length=255, verbose_name='批次'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='销售日期',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='销售日期'),
        ),
    ]
