# Generated by Django 4.1 on 2024-08-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0075_salesrecord_批次_salesrecord_销售日期'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciationallocation',
            name='月份',
            field=models.DateField(default='2024-08-01', verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='expenseallocation',
            name='月份',
            field=models.DateField(default='2024-08-01', verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='备注',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
