# Generated by Django 4.1 on 2024-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0076_alter_depreciationallocation_月份_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_batch',
            name='销毁备注',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
