# Generated by Django 4.1 on 2024-08-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0077_alter_plant_batch_销毁备注'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_batch',
            name='点籽日期',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='移栽日期',
            field=models.DateField(blank=True, null=True),
        ),
    ]
