# Generated by Django 4.1 on 2024-08-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0078_alter_plant_batch_点籽日期_alter_plant_batch_移栽日期'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseallocation',
            name='出勤奖金',
        ),
        migrations.RemoveField(
            model_name='expenseallocation',
            name='燃油费',
        ),
        migrations.RemoveField(
            model_name='expenseallocation',
            name='管理费',
        ),
        migrations.RemoveField(
            model_name='expenseallocation',
            name='维修费',
        ),
        migrations.RemoveField(
            model_name='expenseallocation',
            name='销售费',
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='其他资产',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他资产'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='农家肥',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='农家肥'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='出勤奖',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='出勤奖'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='地租',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='地租'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='地租大棚摊销',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='地租大棚摊销'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='大棚折旧',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='大棚折旧'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='报销费用',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='报销费用'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='散工工时',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='散工工时'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='有机肥',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='有机肥'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='材料费',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='材料费'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='浇水打杂费用',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='浇水打杂费用'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='管理费1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='管理费1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='草莓土',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='草莓土'),
            preserve_default=False,
        ),
    ]
