# Generated by Django 4.1 on 2024-08-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0080_remove_expenseallocation_月份_expenseallocation_批次'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseallocation',
            name='燃油费',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='燃油费'),
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='维修费',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='维修费'),
        ),
        migrations.AddField(
            model_name='expenseallocation',
            name='销售费',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='销售费'),
        ),
    ]
