# Generated by Django 4.1 on 2024-08-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0081_expenseallocation_燃油费_expenseallocation_维修费_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseallocation',
            name='基地经理',
            field=models.CharField(max_length=100),
        ),
    ]
