# Generated by Django 4.1 on 2024-08-22 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0082_alter_expenseallocation_基地经理'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundrecord',
            name='一级分类',
        ),
        migrations.RemoveField(
            model_name='outboundrecord',
            name='二级分类',
        ),
        migrations.RemoveField(
            model_name='outboundrecord',
            name='数量',
        ),
        migrations.RemoveField(
            model_name='outboundrecord',
            name='重量',
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='品种',
            field=models.CharField(default=0, max_length=255, verbose_name='品种'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='品类',
            field=models.CharField(default=0, max_length=255, verbose_name='品类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='客户',
            field=models.CharField(default=0, max_length=255, verbose_name='客户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='挑菜',
            field=models.CharField(default=0, max_length=255, verbose_name='挑菜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='数量_筐',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量/筐'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='盖布_块',
            field=models.CharField(default=0, max_length=255, verbose_name='盖布/块'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='运送数量',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运送数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='重量_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='重量/kg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outboundrecord',
            name='日期',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='日期'),
        ),
    ]
