# Generated by Django 4.1 on 2024-08-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0083_remove_outboundrecord_一级分类_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundrecord',
            name='市场',
            field=models.CharField(max_length=255, verbose_name='市场'),
        ),
        migrations.AlterField(
            model_name='outboundrecord',
            name='车牌',
            field=models.CharField(max_length=255, verbose_name='车牌'),
        ),
    ]
