# Generated by Django 4.1 on 2024-08-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0084_alter_outboundrecord_市场_alter_outboundrecord_车牌'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='单位',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='收款方式',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='收款方式'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='收款日期',
            field=models.DateField(blank=True, null=True, verbose_name='收款日期'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='规格',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='规格'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='销售人员',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='销售人员'),
        ),
    ]
