# Generated by Django 4.1 on 2024-08-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0085_salesrecord_单位_salesrecord_收款方式_salesrecord_收款日期_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitSummary',
            fields=[
                ('批次', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('工时费', models.DecimalField(decimal_places=2, max_digits=10)),
                ('农资费用', models.DecimalField(decimal_places=2, max_digits=10)),
                ('散工工时', models.DecimalField(decimal_places=2, max_digits=10)),
                ('浇水打杂费用', models.DecimalField(decimal_places=2, max_digits=10)),
                ('材料费', models.DecimalField(decimal_places=2, max_digits=10)),
                ('管理费', models.DecimalField(decimal_places=2, max_digits=10)),
                ('生活费', models.DecimalField(decimal_places=2, max_digits=10)),
                ('水电费', models.DecimalField(decimal_places=2, max_digits=10)),
                ('报销费用', models.DecimalField(decimal_places=2, max_digits=10)),
                ('其他费用', models.DecimalField(decimal_places=2, max_digits=10)),
                ('地租', models.DecimalField(decimal_places=2, max_digits=10)),
                ('大棚折旧', models.DecimalField(decimal_places=2, max_digits=10)),
                ('其他资产', models.DecimalField(decimal_places=2, max_digits=10)),
                ('农家肥', models.DecimalField(decimal_places=2, max_digits=10)),
                ('有机肥', models.DecimalField(decimal_places=2, max_digits=10)),
                ('草莓土', models.DecimalField(decimal_places=2, max_digits=10)),
                ('出勤奖', models.DecimalField(decimal_places=2, max_digits=10)),
                ('服务费', models.DecimalField(decimal_places=2, max_digits=10)),
                ('地租大棚摊销', models.DecimalField(decimal_places=2, max_digits=10)),
                ('燃油费', models.DecimalField(decimal_places=2, max_digits=10)),
                ('维修费', models.DecimalField(decimal_places=2, max_digits=10)),
                ('销售费', models.DecimalField(decimal_places=2, max_digits=10)),
                ('销售收入', models.DecimalField(decimal_places=2, max_digits=10)),
                ('利润', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'V_Profit_Summary',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='expenseallocation',
            name='大棚折旧',
        ),
    ]
