# Generated by Django 4.1 on 2024-10-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0086_profitsummary_remove_expenseallocation_大棚折旧'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Profit_Summary',
            fields=[
                ('批次', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('工时费', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('农资费用', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('散工工时', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('浇水打杂费用', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('材料费', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('管理费', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('生活费', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('水电费', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('报销费用', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('其他费用', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('地租', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('其他资产', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('农家肥', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('有机肥', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('草莓土', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('出勤奖金', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('服务费', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('地租大棚摊销', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('燃油费', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('维修费', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('销售费', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('销售收入', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('总成本', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('利润', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'V_Profit_Summary',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProfitSummary',
        ),
        migrations.AlterField(
            model_name='depreciationallocation',
            name='月份',
            field=models.DateField(default='2024-10-01', verbose_name='月份'),
        ),
    ]
