# Generated by Django 4.1 on 2024-10-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0089_jobcategoryinfo_jobtypedetailinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPriceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('日期', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('价格', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('品种', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.jobcategoryinfo', verbose_name='品种')),
                ('市场', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.market', verbose_name='市场')),
            ],
            options={
                'verbose_name': '每日价格上报',
                'verbose_name_plural': '每日价格上报',
            },
        ),
    ]
