# Generated by Django 4.1 on 2024-10-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0090_dailypricereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypricereport',
            name='日期',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
