# Generated by Django 4.1 on 2024-10-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0092_monthlyplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyplan',
            options={},
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='二级分类',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.jobcategoryinfo'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='周期',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='地块',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='基地',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='日期',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='面积',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
