# Generated by Django 4.1 on 2024-10-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0093_alter_monthlyplan_options_alter_monthlyplan_二级分类_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('批次ID', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='批次 ID')),
                ('基地经理', models.CharField(max_length=255, verbose_name='基地经理')),
                ('地块', models.CharField(max_length=255, verbose_name='地块')),
                ('面积', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面积')),
                ('种植日期', models.DateField(verbose_name='种植日期')),
                ('生长周期', models.IntegerField(help_text='单位为天', verbose_name='生长周期')),
                ('采收期', models.IntegerField(help_text='单位为天', verbose_name='采收期')),
                ('采收初期', models.DateField(blank=True, null=True, verbose_name='采收初期')),
                ('采收末期', models.DateField(blank=True, null=True, verbose_name='采收末期')),
                ('备注', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
    ]
