# Generated by Django 4.1 on 2024-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0094_dailyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='未达成反馈',
            field=models.TextField(blank=True, null=True, verbose_name='未达成反馈'),
        ),
    ]
