# Generated by Django 4.1 on 2024-10-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0095_monthlyplan_未达成反馈'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseinfoworkhour',
            name='工种',
        ),
        migrations.AddField(
            model_name='baseinfoworkhour',
            name='一级工种',
            field=models.ForeignKey(blank=True, limit_choices_to={'job_level': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='一级工种', to='app01.jobtypedetailinfo', verbose_name='一级工种'),
        ),
        migrations.AddField(
            model_name='baseinfoworkhour',
            name='二级工种',
            field=models.ForeignKey(blank=True, limit_choices_to={'job_level': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='二级工种', to='app01.jobtypedetailinfo', verbose_name='二级工种'),
        ),
        migrations.AlterField(
            model_name='baseinfoworkhour',
            name='一级分类',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_level': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='一级分类', to='app01.jobcategoryinfo', verbose_name='一级分类'),
        ),
        migrations.AlterField(
            model_name='baseinfoworkhour',
            name='二级分类',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_level': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='二级分类', to='app01.jobcategoryinfo', verbose_name='二级分类'),
        ),
    ]
