# Generated by Django 4.1 on 2024-10-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0096_remove_baseinfoworkhour_工种_baseinfoworkhour_一级工种_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtypedetailinfo',
            name='job_category',
        ),
    ]
