# Generated by Django 4.1 on 2024-11-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0097_remove_jobtypedetailinfo_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_batch',
            name='种植日期',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depreciationallocation',
            name='月份',
            field=models.DateField(default='2024-11-01', verbose_name='月份'),
        ),
    ]
