# Generated by Django 4.1 on 2024-11-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0099_plant_batch_基地_alter_plant_batch_uploader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_batch',
            name='基地',
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='uploader',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='批次ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_batch',
            name='种植日期',
            field=models.DateField(blank=True, null=True),
        ),
    ]
