# Generated by Django 4.1 on 2024-11-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0101_plant_batch_基地_alter_plant_batch_uploader_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agriculture_cost',
            old_name='工种',
            new_name='二级工种',
        ),
        migrations.RenameField(
            model_name='productionwage',
            old_name='工种',
            new_name='一级工种',
        ),
        migrations.AddField(
            model_name='productionwage',
            name='二级工种',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
