# Generated by Django 4.1 on 2024-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0102_rename_工种_agriculture_cost_二级工种_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAlertFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('批次ID', models.CharField(max_length=50)),
                ('工种', models.CharField(blank=True, max_length=255, null=True)),
                ('超额金额', models.DecimalField(decimal_places=2, max_digits=10)),
                ('反馈内容', models.TextField(blank=True, null=True)),
                ('反馈时间', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
