# Generated by Django 4.1 on 2024-11-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0103_costalertfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('批次ID', models.CharField(max_length=50)),
                ('计划内成本', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'views_批次计划内成本',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='costalertfeedback',
            name='超额金额',
        ),
    ]
