# Generated by Django 4.1 on 2024-11-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0104_batchcost_remove_costalertfeedback_超额金额'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('一级分类', models.CharField(max_length=100)),
                ('二级分类', models.CharField(max_length=100)),
                ('一级工种', models.CharField(max_length=100)),
                ('二级工种', models.CharField(max_length=100)),
                ('最小时间', models.PositiveIntegerField(help_text='最小时间（单位：天）')),
                ('最大时间', models.PositiveIntegerField(help_text='最大时间（单位：天）')),
            ],
        ),
    ]
