# Generated by Django 4.1 on 2024-11-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0105_processalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号码'),
        ),
    ]
