# Generated by Django 4.1 on 2024-11-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0106_userinfo_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='身份证号码',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号码'),
        ),
    ]
