# Generated by Django 4.1 on 2024-11-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0107_vehicle_身份证号码'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='市场分类',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.market', verbose_name='市场分类'),
        ),
    ]
