# Generated by Django 4.1 on 2024-11-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0108_vehicle_市场分类'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户管理', 'verbose_name_plural': '客户管理'},
        ),
        migrations.AddField(
            model_name='customer',
            name='主要销售品种',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='主要销售品种'),
        ),
        migrations.AddField(
            model_name='customer',
            name='主要销售地区',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='主要销售地区'),
        ),
        migrations.AddField(
            model_name='customer',
            name='客户流失原因',
            field=models.TextField(blank=True, null=True, verbose_name='客户流失原因'),
        ),
        migrations.AddField(
            model_name='customer',
            name='客户流失时间',
            field=models.DateField(blank=True, null=True, verbose_name='客户流失时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='市场分类',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.market', verbose_name='市场分类'),
        ),
        migrations.AddField(
            model_name='customer',
            name='是否新客户',
            field=models.CharField(choices=[('新客户', '新客户'), ('老客户', '老客户')], default='新客户', max_length=10, verbose_name='是否新客户'),
        ),
    ]
