# Generated by Django 4.1 on 2024-11-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0109_alter_customer_options_customer_主要销售品种_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_batch',
            name='吹生菜周期',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='吹生菜开始时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='吹生菜数量',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='吹生菜结束时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='打地周期',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='打地开始时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='打地数量',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='打地结束时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='施肥周期',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='施肥开始时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='施肥数量',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='施肥结束时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='清棚周期',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='清棚开始时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='清棚数量',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='清棚结束时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='点籽周期',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='点籽开始时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='点籽数量',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='点籽结束时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='移栽周期',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='移栽开始时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='移栽结束时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='采收周期',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='采收开始时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='采收数量',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='采收结束时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='间菜周期',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='间菜开始时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='间菜数量',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='间菜结束时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='除草周期',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='除草开始时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='除草数量',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_batch',
            name='除草结束时间',
            field=models.DateField(blank=True, null=True),
        ),
    ]
