# Generated by Django 4.1 on 2024-11-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0110_plant_batch_吹生菜周期_plant_batch_吹生菜开始时间_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_batch',
            name='移栽日期',
        ),
    ]
