# Generated by Django 4.1 on 2024-11-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0111_remove_plant_batch_移栽日期'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossreport',
            name='备注',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lossreport',
            name='报损面积',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
