# Generated by Django 4.1 on 2024-11-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0112_lossreport_备注_lossreport_报损面积'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyplan',
            name='地块',
        ),
        migrations.RemoveField(
            model_name='monthlyplan',
            name='基地',
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='五天种植单位亩',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='备注',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='每天产量单位吨',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='每天数量单位框',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='每天种植单位亩',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='盘数',
            field=models.IntegerField(default=0),
        ),
    ]
