# Generated by Django 4.1 on 2024-11-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0113_remove_monthlyplan_地块_remove_monthlyplan_基地_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='基地经理',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='生长周期',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='采收初期',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='采收期',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='采收末期',
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='上批批次',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='上批批次'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='下批种植日期',
            field=models.DateField(blank=True, null=True, verbose_name='下批种植日期'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='业主',
            field=models.CharField(default='未知', max_length=255, verbose_name='业主'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='播种方式',
            field=models.CharField(choices=[('移栽', '移栽'), ('点籽', '点籽')], default='移栽', max_length=10, verbose_name='播种方式'),
        ),
    ]
