# Generated by Django 4.1 on 2024-11-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0114_remove_dailyplan_基地经理_remove_dailyplan_生长周期_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='开户行信息'),
        ),
    ]
