# Generated by Django 4.1 on 2024-11-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0115_userinfo_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriculture_cost',
            name='二级工种',
        ),
    ]
