# Generated by Django 4.1 on 2024-12-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0116_remove_agriculture_cost_二级工种'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciationallocation',
            name='月份',
            field=models.DateField(default='2024-12-01', verbose_name='月份'),
        ),
    ]
