# Generated by Django 4.1 on 2024-12-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0118_baseinfoworkhour_上传人_baseinfoworkhour_上传时间_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='excel_file',
            field=models.FileField(default='', max_length=128, upload_to='upload/', verbose_name='excel_file'),
        ),
    ]
