# Generated by Django 4.1 on 2024-12-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0119_alter_uploader_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypricereport',
            name='价格上限',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格上限'),
        ),
    ]
