# Generated by Django 4.1 on 2024-12-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0120_dailypricereport_价格上限'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='销售地区',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='销售地区'),
        ),
    ]
