# Generated by Django 4.1 on 2024-12-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0121_alter_customer_销售地区'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='客户流失时间',
            field=models.TextField(blank=True, null=True, verbose_name='客户流失时间'),
        ),
    ]
