# Generated by Django 4.1 on 2024-12-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0122_alter_customer_客户流失时间'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='创建时间',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
