# Generated by Django 4.1 on 2024-12-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0124_alter_customer_创建时间'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='更新时间',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
