# Generated by Django 4.1 on 2024-12-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0127_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypricereport',
            name='市场',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.channel', verbose_name='渠道'),
        ),
    ]
