# Generated by Django 4.1 on 2024-12-07 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0128_alter_dailypricereport_市场'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundrecord',
            name='数量_筐',
        ),
        migrations.RemoveField(
            model_name='outboundrecord',
            name='运送数量',
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='实收金额',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实收金额'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='实销筐数',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实销筐数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='应收金额',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收金额'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='应销筐数',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='应销筐数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='收款日期',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='日期'),
        ),
    ]
