# Generated by Django 4.1 on 2024-12-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0129_remove_outboundrecord_数量_筐_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundrecord',
            name='实收金额',
        ),
        migrations.RemoveField(
            model_name='outboundrecord',
            name='实销筐数',
        ),
        migrations.RemoveField(
            model_name='outboundrecord',
            name='应收金额',
        ),
        migrations.RemoveField(
            model_name='outboundrecord',
            name='应销筐数',
        ),
        migrations.RemoveField(
            model_name='outboundrecord',
            name='挑菜',
        ),
        migrations.RemoveField(
            model_name='outboundrecord',
            name='收款日期',
        ),
        migrations.AddField(
            model_name='outboundrecord',
            name='数量_筐',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量/筐'),
            preserve_default=False,
        ),
    ]
