# Generated by Django 4.1 on 2024-12-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0130_remove_outboundrecord_实收金额_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundrecord',
            name='客户',
        ),
    ]
