# Generated by Django 4.1 on 2024-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0131_remove_outboundrecord_客户'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='实销筐数',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量'),
        ),
    ]
