# Generated by Django 4.1 on 2024-12-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0132_salesrecord_实销筐数'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='实销筐数',
        ),
    ]
