# Generated by Django 4.1 on 2024-12-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0133_remove_salesrecord_实销筐数'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='实销筐数',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实销筐数'),
        ),
    ]
